from typing import Any, Awaitable, Callable, Iterator, Literal, Optional, Sequence, Union

__version__: str

Command = Union[str, Sequence[str]]
StdioMode = Literal["pipe", "null", "inherit"]

class TuesError(Exception): ...
class ConnectError(TuesError): ...
class AuthError(TuesError): ...
class HostKeyError(TuesError): ...
class SudoError(TuesError): ...
class SftpError(TuesError): ...

class PasswordRequest:
    @property
    def kind(self) -> Literal["login", "sudo", "key_passphrase"]: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def user(self) -> str: ...
    @property
    def run_as(self) -> Optional[str]: ...
    @property
    def key_path(self) -> Optional[str]: ...
    @property
    def prompt(self) -> str: ...

PasswordSource = Union[Callable[[PasswordRequest], str], Any]

class ExitStatus:
    @property
    def code(self) -> Optional[int]: ...
    @property
    def signal(self) -> Optional[str]: ...
    @property
    def success(self) -> bool: ...
    def __bool__(self) -> bool: ...

class Output:
    status: ExitStatus
    stdout: bytes
    stderr: bytes
    @property
    def returncode(self) -> Optional[int]: ...
    @property
    def success(self) -> bool: ...
    def text(self) -> str: ...

class Metadata:
    @property
    def size(self) -> int: ...
    @property
    def is_dir(self) -> bool: ...
    @property
    def is_file(self) -> bool: ...
    @property
    def is_symlink(self) -> bool: ...
    @property
    def mode(self) -> Optional[int]: ...
    @property
    def permissions(self) -> Optional[int]: ...
    @property
    def uid(self) -> Optional[int]: ...
    @property
    def gid(self) -> Optional[int]: ...
    @property
    def mtime(self) -> Optional[float]: ...
    @property
    def atime(self) -> Optional[float]: ...

class DirEntry:
    name: str
    metadata: Metadata

# --------------------------------------------------------------------------
# Blocking API
# --------------------------------------------------------------------------

class Session:
    @staticmethod
    def connect(
        destination: str,
        *,
        user: Optional[str] = ...,
        port: Optional[int] = ...,
        run_as: Optional[str] = ...,
        host_name: Optional[str] = ...,
        identity_files: Optional[Sequence[str]] = ...,
        identities_only: Optional[bool] = ...,
        proxy_jump: Optional[str] = ...,
        connect_timeout: Optional[float] = ...,
        server_alive_interval: Optional[float] = ...,
        compression: Optional[bool] = ...,
        use_agent: Optional[bool] = ...,
        pubkey_authentication: Optional[bool] = ...,
        password_authentication: Optional[bool] = ...,
        host_key_policy: Optional[Literal["strict", "accept-new", "off"]] = ...,
        known_hosts_file: Optional[str] = ...,
        ssh_config: Union[None, bool, str] = ...,
        password: Optional[str] = ...,
        password_manager: Optional[PasswordSource] = ...,
    ) -> "Session": ...
    @property
    def user(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def run_as(self) -> Optional[str]: ...
    @property
    def closed(self) -> bool: ...
    def run(
        self,
        cmd: Command,
        *,
        run_as: Optional[str] = ...,
        run_as_login_user: bool = ...,
        pty: bool = ...,
        env: Optional[dict[str, Optional[str]]] = ...,
        cwd: Optional[str] = ...,
        input: Optional[bytes] = ...,
        check: bool = ...,
    ) -> Output: ...
    def spawn(
        self,
        cmd: Command,
        *,
        run_as: Optional[str] = ...,
        run_as_login_user: bool = ...,
        pty: bool = ...,
        env: Optional[dict[str, Optional[str]]] = ...,
        cwd: Optional[str] = ...,
        stdin: StdioMode = ...,
        stdout: StdioMode = ...,
        stderr: StdioMode = ...,
    ) -> "Child": ...
    def sftp(self) -> "Sftp": ...
    def close(self) -> None: ...
    def __enter__(self) -> "Session": ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> bool: ...

class Child:
    @property
    def stdin(self) -> Optional["ChildStdin"]: ...
    @property
    def stdout(self) -> Optional["ChildStdout"]: ...
    @property
    def stderr(self) -> Optional["ChildStdout"]: ...
    def wait(self) -> ExitStatus: ...
    def poll(self) -> Optional[ExitStatus]: ...
    def kill(self) -> None: ...
    def communicate(self, input: Optional[bytes] = ...) -> tuple[bytes, bytes]: ...

class ChildStdin:
    def write(self, data: bytes) -> int: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def __enter__(self) -> "ChildStdin": ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> bool: ...

class ChildStdout:
    def read(self, n: int = ...) -> bytes: ...
    def read_exact(self, n: int) -> bytes: ...
    def readline(self) -> bytes: ...
    def __iter__(self) -> Iterator[bytes]: ...
    def __next__(self) -> bytes: ...

class Sftp:
    def read(self, path: str) -> bytes: ...
    def read_text(self, path: str) -> str: ...
    def write(self, path: str, data: bytes) -> None: ...
    def open(self, path: str, mode: str = ...) -> "File": ...
    def listdir(self, path: str) -> list[DirEntry]: ...
    def mkdir(self, path: str) -> None: ...
    def remove(self, path: str) -> None: ...
    def rmdir(self, path: str) -> None: ...
    def rename(self, src: str, dst: str) -> None: ...
    def symlink(self, target: str, link: str) -> None: ...
    def readlink(self, path: str) -> str: ...
    def stat(self, path: str) -> Metadata: ...
    def lstat(self, path: str) -> Metadata: ...
    def exists(self, path: str) -> bool: ...
    def realpath(self, path: str) -> str: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Sftp": ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> bool: ...

class File:
    def read(self, n: int = ...) -> bytes: ...
    def write(self, data: bytes) -> int: ...
    def seek(self, offset: int, whence: int = ...) -> int: ...
    def tell(self) -> int: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def __enter__(self) -> "File": ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> bool: ...

# --------------------------------------------------------------------------
# asyncio API
# --------------------------------------------------------------------------

class AsyncSession:
    @staticmethod
    def connect(
        destination: str,
        *,
        user: Optional[str] = ...,
        port: Optional[int] = ...,
        run_as: Optional[str] = ...,
        host_name: Optional[str] = ...,
        identity_files: Optional[Sequence[str]] = ...,
        identities_only: Optional[bool] = ...,
        proxy_jump: Optional[str] = ...,
        connect_timeout: Optional[float] = ...,
        server_alive_interval: Optional[float] = ...,
        compression: Optional[bool] = ...,
        use_agent: Optional[bool] = ...,
        pubkey_authentication: Optional[bool] = ...,
        password_authentication: Optional[bool] = ...,
        host_key_policy: Optional[Literal["strict", "accept-new", "off"]] = ...,
        known_hosts_file: Optional[str] = ...,
        ssh_config: Union[None, bool, str] = ...,
        password: Optional[str] = ...,
        password_manager: Optional[PasswordSource] = ...,
    ) -> Awaitable["AsyncSession"]: ...
    @property
    def user(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def run_as(self) -> Optional[str]: ...
    @property
    def closed(self) -> bool: ...
    def run(
        self,
        cmd: Command,
        *,
        run_as: Optional[str] = ...,
        run_as_login_user: bool = ...,
        pty: bool = ...,
        env: Optional[dict[str, Optional[str]]] = ...,
        cwd: Optional[str] = ...,
        input: Optional[bytes] = ...,
        check: bool = ...,
    ) -> Awaitable[Output]: ...
    def spawn(
        self,
        cmd: Command,
        *,
        run_as: Optional[str] = ...,
        run_as_login_user: bool = ...,
        pty: bool = ...,
        env: Optional[dict[str, Optional[str]]] = ...,
        cwd: Optional[str] = ...,
        stdin: StdioMode = ...,
        stdout: StdioMode = ...,
        stderr: StdioMode = ...,
    ) -> Awaitable["AsyncChild"]: ...
    def sftp(self) -> Awaitable["AsyncSftp"]: ...
    def close(self) -> Awaitable[None]: ...
    def __aenter__(self) -> Awaitable["AsyncSession"]: ...
    def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> Awaitable[bool]: ...

class AsyncChild:
    @property
    def stdin(self) -> Optional["AsyncChildStdin"]: ...
    @property
    def stdout(self) -> Optional["AsyncChildStdout"]: ...
    @property
    def stderr(self) -> Optional["AsyncChildStdout"]: ...
    def wait(self) -> Awaitable[ExitStatus]: ...
    def poll(self) -> Optional[ExitStatus]: ...
    def kill(self) -> None: ...
    def communicate(self, input: Optional[bytes] = ...) -> Awaitable[tuple[bytes, bytes]]: ...

class AsyncChildStdin:
    def write(self, data: bytes) -> Awaitable[int]: ...
    def close(self) -> Awaitable[None]: ...

class AsyncChildStdout:
    def read(self, n: int = ...) -> Awaitable[bytes]: ...
    def read_exact(self, n: int) -> Awaitable[bytes]: ...
    def readline(self) -> Awaitable[bytes]: ...

class AsyncSftp:
    def read(self, path: str) -> Awaitable[bytes]: ...
    def read_text(self, path: str) -> Awaitable[str]: ...
    def write(self, path: str, data: bytes) -> Awaitable[None]: ...
    def open(self, path: str, mode: str = ...) -> Awaitable["AsyncFile"]: ...
    def listdir(self, path: str) -> Awaitable[list[DirEntry]]: ...
    def mkdir(self, path: str) -> Awaitable[None]: ...
    def remove(self, path: str) -> Awaitable[None]: ...
    def rmdir(self, path: str) -> Awaitable[None]: ...
    def rename(self, src: str, dst: str) -> Awaitable[None]: ...
    def symlink(self, target: str, link: str) -> Awaitable[None]: ...
    def readlink(self, path: str) -> Awaitable[str]: ...
    def stat(self, path: str) -> Awaitable[Metadata]: ...
    def lstat(self, path: str) -> Awaitable[Metadata]: ...
    def exists(self, path: str) -> Awaitable[bool]: ...
    def realpath(self, path: str) -> Awaitable[str]: ...
    def close(self) -> Awaitable[None]: ...
    def __aenter__(self) -> Awaitable["AsyncSftp"]: ...
    def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> Awaitable[bool]: ...

class AsyncFile:
    def read(self, n: int = ...) -> Awaitable[bytes]: ...
    def write(self, data: bytes) -> Awaitable[int]: ...
    def seek(self, offset: int, whence: int = ...) -> Awaitable[int]: ...
    def tell(self) -> Awaitable[int]: ...
    def flush(self) -> Awaitable[None]: ...
    def close(self) -> Awaitable[None]: ...
    @property
    def closed(self) -> bool: ...
    def __aenter__(self) -> Awaitable["AsyncFile"]: ...
    def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> Awaitable[bool]: ...
