#!/usr/bin/env python
# coding: utf-8

import click as _click


@_click.command()
@_click.argument("hosts", nargs=-1, type=unicode, help="Hosts to return")
def cli(hosts):
    """ Just return the hosts passed on the commandline """
    _click.echo(u"\n".join(hosts))


if __name__ == "__main__":
    cli()
