#!/usr/bin/env python
# coding: utf-8
"""Usage:
tues-provider-file <path>

Options:
  <path>                   Path to a file containing newline seperated hostnames
"""

import docopt as _docopt

if __name__ == '__main__':
    args = _docopt.docopt(__doc__)
    print open(args["<path>"]).read()
