#!/usr/bin/env python
# coding: utf-8

import click as _click


@_click.command()
@_click.argument("path", type=_click.Path(readable=True, dir_okay=False, file_okay=True))
def cli(path):
    _click.echo(open(path).read())


if __name__ == "__main__":
    cli()
