#!/usr/bin/env python
# coding: utf-8
"""Usage:
tues-provider-fm [--foreman-url=<url>] <expression>

Options:
  <expression>                   The foreman filter expression.
  --foreman-url=<url>            URL to your foreman installation.
"""

import os as _os

import docopt as _docopt
import requests as _requests


def hosts(query, url):
    hosts = _requests.get(
        url,
        params={"search": query, "per_page": 10000},
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
    ).json()
    return [host['host']['name'] for host in hosts]


if __name__ == '__main__':
    args = _docopt.docopt(__doc__)
    foreman_url = args["--foreman-url"] or _os.environ.get("FOREMAN_URL")

    if not foreman_url:
        raise Exception(
            "You need to provide a foreman url either by setting FOREMAN_URL or passing --foreman-url"
        )

    hosts = hosts(args['<expression>'], foreman_url + "/api/hosts")
    print "\n".join(hosts)
